// Code generated by protoc-gen-go. DO NOT EDIT.
// source: todo.proto

package rpctodo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// CreateTodo:Params
type CreateTodoParams struct {
	Todo                 *Todo    `protobuf:"bytes,1,opt,name=todo,proto3" json:"todo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTodoParams) Reset()         { *m = CreateTodoParams{} }
func (m *CreateTodoParams) String() string { return proto.CompactTextString(m) }
func (*CreateTodoParams) ProtoMessage()    {}
func (*CreateTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{0}
}

func (m *CreateTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTodoParams.Unmarshal(m, b)
}
func (m *CreateTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTodoParams.Marshal(b, m, deterministic)
}
func (m *CreateTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTodoParams.Merge(m, src)
}
func (m *CreateTodoParams) XXX_Size() int {
	return xxx_messageInfo_CreateTodoParams.Size(m)
}
func (m *CreateTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTodoParams proto.InternalMessageInfo

func (m *CreateTodoParams) GetTodo() *Todo {
	if m != nil {
		return m.Todo
	}
	return nil
}

// GetTodo:Params
type GetTodoParams struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTodoParams) Reset()         { *m = GetTodoParams{} }
func (m *GetTodoParams) String() string { return proto.CompactTextString(m) }
func (*GetTodoParams) ProtoMessage()    {}
func (*GetTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{1}
}

func (m *GetTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTodoParams.Unmarshal(m, b)
}
func (m *GetTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTodoParams.Marshal(b, m, deterministic)
}
func (m *GetTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTodoParams.Merge(m, src)
}
func (m *GetTodoParams) XXX_Size() int {
	return xxx_messageInfo_GetTodoParams.Size(m)
}
func (m *GetTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_GetTodoParams proto.InternalMessageInfo

func (m *GetTodoParams) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

// UpdateTodo:Params
type UpdateTodoParams struct {
	Id                   int64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDone               *wrappers.BoolValue   `protobuf:"bytes,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	IsDeleted            *wrappers.BoolValue   `protobuf:"bytes,4,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateTodoParams) Reset()         { *m = UpdateTodoParams{} }
func (m *UpdateTodoParams) String() string { return proto.CompactTextString(m) }
func (*UpdateTodoParams) ProtoMessage()    {}
func (*UpdateTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{2}
}

func (m *UpdateTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTodoParams.Unmarshal(m, b)
}
func (m *UpdateTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTodoParams.Marshal(b, m, deterministic)
}
func (m *UpdateTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTodoParams.Merge(m, src)
}
func (m *UpdateTodoParams) XXX_Size() int {
	return xxx_messageInfo_UpdateTodoParams.Size(m)
}
func (m *UpdateTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTodoParams proto.InternalMessageInfo

func (m *UpdateTodoParams) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateTodoParams) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateTodoParams) GetIsDone() *wrappers.BoolValue {
	if m != nil {
		return m.IsDone
	}
	return nil
}

func (m *UpdateTodoParams) GetIsDeleted() *wrappers.BoolValue {
	if m != nil {
		return m.IsDeleted
	}
	return nil
}

// DeleteTodo:Params
type DeleteTodoParams struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteTodoParams) Reset()         { *m = DeleteTodoParams{} }
func (m *DeleteTodoParams) String() string { return proto.CompactTextString(m) }
func (*DeleteTodoParams) ProtoMessage()    {}
func (*DeleteTodoParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{3}
}

func (m *DeleteTodoParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteTodoParams.Unmarshal(m, b)
}
func (m *DeleteTodoParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteTodoParams.Marshal(b, m, deterministic)
}
func (m *DeleteTodoParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteTodoParams.Merge(m, src)
}
func (m *DeleteTodoParams) XXX_Size() int {
	return xxx_messageInfo_DeleteTodoParams.Size(m)
}
func (m *DeleteTodoParams) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteTodoParams.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteTodoParams proto.InternalMessageInfo

func (m *DeleteTodoParams) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Todo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	IsDone               bool     `protobuf:"varint,2,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	CreatedAt            string   `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            string   `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsDeleted            bool     `protobuf:"varint,5,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	Id                   int64    `protobuf:"varint,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Todo) Reset()         { *m = Todo{} }
func (m *Todo) String() string { return proto.CompactTextString(m) }
func (*Todo) ProtoMessage()    {}
func (*Todo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e4b95d0c4e09639, []int{4}
}

func (m *Todo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Todo.Unmarshal(m, b)
}
func (m *Todo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Todo.Marshal(b, m, deterministic)
}
func (m *Todo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Todo.Merge(m, src)
}
func (m *Todo) XXX_Size() int {
	return xxx_messageInfo_Todo.Size(m)
}
func (m *Todo) XXX_DiscardUnknown() {
	xxx_messageInfo_Todo.DiscardUnknown(m)
}

var xxx_messageInfo_Todo proto.InternalMessageInfo

func (m *Todo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Todo) GetIsDone() bool {
	if m != nil {
		return m.IsDone
	}
	return false
}

func (m *Todo) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

func (m *Todo) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *Todo) GetIsDeleted() bool {
	if m != nil {
		return m.IsDeleted
	}
	return false
}

func (m *Todo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateTodoParams)(nil), "pepeunlimited.todo.CreateTodoParams")
	proto.RegisterType((*GetTodoParams)(nil), "pepeunlimited.todo.GetTodoParams")
	proto.RegisterType((*UpdateTodoParams)(nil), "pepeunlimited.todo.UpdateTodoParams")
	proto.RegisterType((*DeleteTodoParams)(nil), "pepeunlimited.todo.DeleteTodoParams")
	proto.RegisterType((*Todo)(nil), "pepeunlimited.todo.Todo")
}

func init() { proto.RegisterFile("todo.proto", fileDescriptor_0e4b95d0c4e09639) }

var fileDescriptor_0e4b95d0c4e09639 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0xbd, 0x8e, 0xda, 0x40,
	0x10, 0x96, 0x8d, 0x81, 0x78, 0x50, 0x22, 0xb4, 0x4d, 0x2c, 0xe7, 0xdf, 0x4a, 0x91, 0x22, 0x32,
	0x11, 0x54, 0xe9, 0x12, 0x82, 0x92, 0x86, 0x22, 0x32, 0x49, 0x8a, 0x34, 0xc8, 0xb0, 0x13, 0xb4,
	0x92, 0xed, 0x5d, 0xad, 0xd7, 0x39, 0xdd, 0xdb, 0xdc, 0x9b, 0x5c, 0x73, 0x0f, 0x76, 0xda, 0x5d,
	0x73, 0x06, 0x63, 0xb8, 0xce, 0xda, 0xef, 0x67, 0xbe, 0xf1, 0x7c, 0x00, 0x8a, 0x53, 0x1e, 0x0b,
	0xc9, 0x15, 0x27, 0x44, 0xa0, 0xc0, 0xaa, 0xc8, 0x58, 0xce, 0x14, 0xd2, 0x58, 0x23, 0xe1, 0x8b,
	0x1d, 0xe7, 0xbb, 0x0c, 0x27, 0x86, 0xb1, 0xa9, 0xfe, 0x4d, 0x30, 0x17, 0xea, 0xda, 0x0a, 0xc2,
	0xd7, 0x6d, 0xf0, 0x4a, 0xa6, 0x42, 0xa0, 0x2c, 0x2d, 0x1e, 0x7d, 0x81, 0xf1, 0x37, 0x89, 0xa9,
	0xc2, 0x5f, 0x9c, 0xf2, 0x9f, 0xa9, 0x4c, 0xf3, 0x92, 0x7c, 0x04, 0x4f, 0x1b, 0x07, 0xce, 0x5b,
	0xe7, 0xc3, 0x68, 0x1a, 0xc4, 0xa7, 0x33, 0x63, 0xcd, 0x4e, 0x0c, 0x2b, 0x7a, 0x03, 0x4f, 0x7f,
	0xa0, 0x3a, 0x90, 0x3f, 0x03, 0x97, 0x51, 0x23, 0xee, 0x25, 0x2e, 0xa3, 0xd1, 0x9d, 0x03, 0xe3,
	0xdf, 0x82, 0x1e, 0xcf, 0x68, 0x91, 0xc8, 0x27, 0xf0, 0x8a, 0x34, 0xc7, 0xc0, 0x35, 0x33, 0x5f,
	0xc6, 0x36, 0x76, 0xbc, 0x8f, 0x1d, 0xaf, 0x94, 0x64, 0xc5, 0xee, 0x4f, 0x9a, 0x55, 0x98, 0x18,
	0x26, 0x99, 0xc1, 0x90, 0x95, 0x6b, 0xca, 0x0b, 0x0c, 0x7a, 0x46, 0x14, 0x9e, 0x88, 0xe6, 0x9c,
	0x67, 0x56, 0x32, 0x60, 0xe5, 0x82, 0x17, 0x48, 0x3e, 0x03, 0x68, 0x11, 0x66, 0xa8, 0x90, 0x06,
	0xde, 0xa3, 0x3a, 0x9f, 0x95, 0x0b, 0x4b, 0x8e, 0x22, 0x18, 0xdb, 0xcf, 0x0b, 0xab, 0xde, 0x38,
	0xe0, 0x69, 0x98, 0x90, 0x7a, 0x1d, 0x0d, 0xf9, 0x75, 0xe0, 0xe7, 0x4d, 0x60, 0xbd, 0xe5, 0x93,
	0x87, 0x50, 0xaf, 0x00, 0xb6, 0xe6, 0x06, 0x74, 0x9d, 0x2a, 0xb3, 0x8c, 0x9f, 0xf8, 0xf5, 0xcb,
	0x57, 0xa5, 0xe1, 0xca, 0xfc, 0x3e, 0x03, 0x7b, 0x16, 0xae, 0x5f, 0x2c, 0x7c, 0xb0, 0x52, 0xdf,
	0x38, 0x37, 0xb1, 0xeb, 0x88, 0x83, 0x7d, 0xc4, 0xe9, 0xad, 0x0b, 0x23, 0x1d, 0x71, 0x85, 0xf2,
	0x3f, 0xdb, 0x22, 0x59, 0x02, 0x34, 0x05, 0x20, 0xef, 0xbb, 0x8e, 0xdd, 0x2e, 0x48, 0x78, 0xb6,
	0x12, 0xe4, 0x3b, 0x0c, 0xeb, 0x32, 0x90, 0x77, 0x5d, 0xa4, 0xa3, 0xa6, 0x5c, 0xf0, 0x59, 0x02,
	0x34, 0x95, 0xe9, 0x4e, 0xd5, 0xae, 0xd4, 0x65, 0xb7, 0xe6, 0x74, 0xdd, 0x6e, 0xed, 0xd3, 0x9e,
	0x77, 0x9b, 0xf7, 0xff, 0xf6, 0xa4, 0xd8, 0x6e, 0x06, 0xa6, 0x2e, 0xb3, 0xfb, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x64, 0x74, 0xe5, 0x24, 0x9f, 0x03, 0x00, 0x00,
}
